import './styles.css';
const W=960,H=540,canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const ui={hp:document.getElementById('hp'),lv:document.getElementById('lv'),score:document.getElementById('score'),time:document.getElementById('time'),restart:document.getElementById('restart')};
const ENEMIES={chicken:{name:'鶏',hp:18,spd:58,score:6,color:'#f2f0d6',accent:'#d43126',size:19},boar:{name:'猪',hp:34,spd:45,score:12,color:'#6b4738',accent:'#d9c0a0',size:24},hound:{name:'ハウンド',hp:26,spd:76,score:10,color:'#40424c',accent:'#d9d9e2',size:23},bear:{name:'クマ',hp:90,spd:32,score:35,color:'#4a3028',accent:'#c49258',size:34}};
const waves=['chicken','boar','hound','bear'],keys={},clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
let game,touch=null,shake=0,raf=0;
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='r')start();});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);ui.restart.onclick=start;
document.body.addEventListener('touchstart',e=>{const t=e.touches[0];touch={sx:t.clientX,sy:t.clientY,dx:0,dy:0}},{passive:false});
document.body.addEventListener('touchmove',e=>{const t=e.touches[0];if(!touch)return;touch.dx=clamp((t.clientX-touch.sx)/48,-1,1);touch.dy=clamp((t.clientY-touch.sy)/48,-1,1);e.preventDefault()},{passive:false});
document.body.addEventListener('touchend',()=>touch=null);
function start(){game={player:{x:W/2,y:H/2,hp:100,inv:0,level:1,xp:0,need:24,fire:0,angle:0},enemies:[],shots:[],sparks:[],score:0,time:0,last:performance.now(),state:'playing',spawn:0};cancelAnimationFrame(raf);raf=requestAnimationFrame(step)}
function step(now){const dt=Math.min(.033,(now-game.last)/1000);game.last=now;update(dt);draw();raf=requestAnimationFrame(step)}
function update(dt){if(game.state!=='playing')return;game.time+=dt;const p=game.player;let ax=0,ay=0;if(keys.arrowleft||keys.a)ax--;if(keys.arrowright||keys.d)ax++;if(keys.arrowup||keys.w)ay--;if(keys.arrowdown||keys.s)ay++;if(touch){ax=touch.dx;ay=touch.dy}const len=Math.hypot(ax,ay)||1;p.x=clamp(p.x+ax/len*178*dt,24,W-24);p.y=clamp(p.y+ay/len*178*dt,28,H-28);if(ax||ay)p.angle=Math.atan2(ay,ax);game.spawn-=dt;if(game.spawn<=0){spawn();game.spawn=Math.max(.18,1-game.time/80)}p.fire-=dt;if(p.fire<=0){autoShoot();p.fire=Math.max(.16,.48-p.level*.025)}for(const s of game.shots){s.x+=Math.cos(s.a)*s.v*dt;s.y+=Math.sin(s.a)*s.v*dt;s.life-=dt}game.shots=game.shots.filter(s=>s.life>0&&s.x>-20&&s.x<W+20&&s.y>-20&&s.y<H+20);for(const e of game.enemies){const a=Math.atan2(p.y-e.y,p.x-e.x);e.x+=Math.cos(a)*e.spd*dt;e.y+=Math.sin(a)*e.spd*dt;e.frame+=dt*8;if(dist(e,p)<e.size+18&&p.inv<=0){p.hp-=9;p.inv=.75;shake=8}}p.inv-=dt;for(const s of game.shots)for(const e of game.enemies)if(!s.hit&&dist(s,e)<e.size){s.hit=true;e.hp-=s.dmg;game.sparks.push({x:e.x,y:e.y,life:.25,c:e.accent})}game.shots=game.shots.filter(s=>!s.hit);const dead=game.enemies.filter(e=>e.hp<=0);for(const e of dead){game.score+=e.score;p.xp+=e.score;game.sparks.push({x:e.x,y:e.y,life:.45,c:'#ffd45a'})}game.enemies=game.enemies.filter(e=>e.hp>0);if(p.xp>=p.need){p.xp-=p.need;p.level++;p.need=Math.floor(p.need*1.35);p.hp=clamp(p.hp+18,0,100)}for(const sp of game.sparks)sp.life-=dt;game.sparks=game.sparks.filter(s=>s.life>0);if(p.hp<=0){game.state='over';ui.restart.textContent='再挑戦'}ui.hp.textContent=`HP ${Math.max(0,Math.ceil(p.hp))}`;ui.lv.textContent=`Lv ${p.level}`;ui.score.textContent=`Score ${game.score}`;ui.time.textContent=`${Math.floor(game.time)}s`}
function spawn(){const t=waves[Math.min(3,Math.floor(game.time/25))],side=Math.floor(Math.random()*4),e={type:t,...ENEMIES[t],hp:ENEMIES[t].hp+game.time*.35,frame:0};e.x=side<2?rnd(0,W):side===2?-30:W+30;e.y=side<2?(side?H+30:-30):rnd(0,H);game.enemies.push(e)}
function autoShoot(){let target=null,b=9999;for(const e of game.enemies){const d=dist(game.player,e);if(d<b){b=d;target=e}}const a=target?Math.atan2(target.y-game.player.y,target.x-game.player.x):game.player.angle;for(let i=0;i<Math.min(3,1+Math.floor(game.player.level/4));i++)game.shots.push({x:game.player.x,y:game.player.y,a:a+(i-1)*.14,v:430,life:1.2,dmg:20+game.player.level*2})}
function draw(){canvas.width=W;canvas.height=H;ctx.imageSmoothingEnabled=false;ctx.fillStyle='#17351f';ctx.fillRect(0,0,W,H);ctx.save();if(shake>0){ctx.translate(rnd(-shake,shake),rnd(-shake,shake));shake*=.85}grid();for(const sp of game.sparks){ctx.fillStyle=sp.c;ctx.fillRect(sp.x-8,sp.y-8,16,16)}for(const e of game.enemies)enemy(e);for(const s of game.shots){ctx.fillStyle='#88f1ff';ctx.fillRect(s.x-4,s.y-4,8,8)}player(game.player);ctx.restore();if(game.state==='over')overlay('GAME OVER','画面タップ・Rキー・再挑戦ボタンで再挑戦')}
function grid(){ctx.fillStyle='#214a2c';for(let x=0;x<W;x+=48)for(let y=0;y<H;y+=48)ctx.fillRect(x+22,y+22,4,4)}
function px(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h)}
function player(p){ctx.save();ctx.translate(p.x,p.y);if(p.inv>0&&Math.floor(p.inv*20)%2)ctx.globalAlpha=.45;px(-9,-26,18,10,'#ff433a');px(-13,-18,26,22,'#5b3434');px(-7,-14,14,20,'#f4f4ef');px(-10,-31,20,10,'#ff2d25');px(6,-25,9,5,'#b01622');px(-5,-22,10,9,'#f1c7a0');px(-19,-5,10,23,'#563032');px(9,-5,10,23,'#563032');px(-16,17,11,28,'#4a292a');px(5,17,11,28,'#4a292a');px(-21,42,19,9,'#e94132');px(4,42,19,9,'#e94132');px(-28,-13,18,8,'#e94132');px(14,-11,34,8,'#30343d');px(45,-13,25,18,'#596070');px(50,-22,15,9,'#596070');ctx.restore()}
function enemy(e){ctx.save();ctx.translate(e.x,e.y);const bob=Math.sin(e.frame)*2;if(e.type==='chicken'){px(-8,bob-9,16,14,e.color);px(-2,bob-18,10,10,e.color);px(4,bob-23,6,6,e.accent);px(7,bob-15,8,4,'#e7a52e');px(-6,bob+5,3,9,'#d89025');px(4,bob+5,3,9,'#d89025')}else if(e.type==='boar'){px(-15,bob-9,30,18,e.color);px(8,bob-14,14,14,e.color);px(16,bob-6,8,6,e.accent);px(17,bob-11,5,4,'#111');px(-12,bob+8,5,9,'#2a1b18');px(7,bob+8,5,9,'#2a1b18')}else if(e.type==='hound'){px(-16,bob-10,32,16,e.color);px(10,bob-18,14,14,e.color);px(14,bob-26,5,9,e.color);px(19,bob-7,9,5,e.accent);px(-11,bob+6,5,13,'#222');px(8,bob+6,5,13,'#222')}else{px(-22,bob-20,44,34,e.color);px(-15,bob-33,30,18,e.color);px(-18,bob-38,8,8,e.color);px(10,bob-38,8,8,e.color);px(-6,bob-25,12,8,e.accent);px(-28,bob-8,10,22,e.color);px(18,bob-8,10,22,e.color)}ctx.restore()}
function overlay(a,b){ctx.fillStyle='rgba(0,0,0,.55)';ctx.fillRect(0,0,W,H);ctx.fillStyle='white';ctx.textAlign='center';ctx.font='48px monospace';ctx.fillText(a,W/2,H/2);ctx.font='20px monospace';ctx.fillText(b,W/2,H/2+40)}
start();
